{% set name = "guacamol" %}
{% set version = "0.5.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/guacamol-{{ version }}.tar.gz
  sha256: b6152472a8d6dc75f1ee3cce83233a9a1ba0558d43b6a8ce55a8299b46b2828b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python
    - joblib >=0.12.5
    - numpy >=1.15.2
    - scipy >=1.1.0
    - tqdm >=4.26.0
    - fcd >=1.1
    - rdkit

test:
  imports:
    - guacamol
    - guacamol.data
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/BenevolentAI/guacamol
  summary: 'Guacamol: benchmarks for de novo molecular design'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
